{% set name = "ryven" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ryven-{{ version }}.tar.gz
  sha256: 7e2e47ba3e4d06b2cd961a89655dd314fe97576b487acaba57540bd7b57da5fd

build:
  number: 1
  noarch: python
  entry_points:
    - ryven = ryven:run_ryven
    - ryven_console = ryven:run_ryven_console
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - jinja2
    - pygments
    - python >={{ python_min }}
    - ryvencore ==0.4.*
    - ryvencore-qt ==0.4.*
    - textdistance
    - packaging

test:
  requires:
    - python {{ python_min }}
  imports:
    - ryven
    - ryven.gui

about:
  home: https://github.com/leon-thomm/Ryven
  summary: Flow-based visual scripting for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - leon-thomm
    - jan-janssen
