{% set name = "ryven" %}
{% set version = "3.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ryven-{{ version }}.tar.gz
  sha256: 05319c0627589bcfc7cf4c571711a029e9aca9f4e4039990ea5a0f9de48faa25

build:
  number: 0
  noarch: python
  entry_points:
    - ryven = ryven:run_ryven
    - ryven_console = ryven:run_ryven_console
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >3.6,<=3.10
  run:
    - jinja2
    - pygments
    - python >3.6,!=3.10
    - ryvencore ==0.4.*
    - ryvencore-qt ==0.4.*
    - textdistance
    - packaging

test:
  imports:
    - ryven
    - ryven.gui

about:
  home: https://github.com/leon-thomm/Ryven
  summary: Flow-based visual scripting for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - leon-thomm
    - jan-janssen
